# Podfile for iOS Project
# Minimum deployment target set to iOS 18.0 for latest Xcode compatibility

platform :ios, '18.0'

# Uncomment the next line if you're using Swift or want to use dynamic frameworks
use_frameworks!

# Replace 'YourProjectName' with your actual target name
# You can find this in Xcode under TARGETS
target 'YourProjectName' do
  
  # Uncomment any pods you need for your project:
  
  # Networking
  # pod 'AFNetworking', '~> 4.0'
  # pod 'Alamofire', '~> 5.0'
  
  # JSON parsing
  # pod 'SwiftyJSON', '~> 5.0'
  
  # Image loading and caching
  # pod 'SDWebImage', '~> 5.0'
  # pod 'Kingfisher', '~> 7.0'
  
  # UI Components
  # pod 'MBProgressHUD', '~> 1.2'
  
  # Auto Layout
  # pod 'SnapKit', '~> 5.0'
  # pod 'Masonry', '~> 1.1'
  
  # Reachability (if needed, though iOS has built-in alternatives)
  # Note: The Reachability files appear to be included directly in your project
  
end

# This post_install hook ensures all pods use the correct deployment target
# This is crucial for fixing the libarclite error
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Set minimum deployment target to iOS 18.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
      
      # Disable bitcode (deprecated in Xcode 14+)
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      
      # Set Swift version if needed
      # config.build_settings['SWIFT_VERSION'] = '5.9'
    end
  end
  
  # Fix for Xcode 15+ warnings
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        xcconfig_path = config.base_configuration_reference
        if xcconfig_path
          xcconfig = File.read(xcconfig_path.real_path)
          xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
          File.open(xcconfig_path.real_path, "w") { |file| file << xcconfig_mod }
        end
      end
    end
  end
end
